### ISSUE TITLE
a problem in colab

### ISSUE THREAD

**Issue by user-kay** [VinAIResearch/CPM#10]
when I run it in colab, I faced a problem like this
![b99d270aa1cbc4ed9f15d5a1290be93](https://user-images.githubusercontent.com/63137588/129605772-5df69677-89b8-4bcf-94f3-3a476eb37d34.png)
Can you tell me how to solve it?

**Comment by thaoshibe** [comment]
Sorry for the inconvenience you're facing.
I have just checked the Colab, and you're right. Thank you for notify me.

There must be someone who forgot to create a Copy of the Notebook BEFORE running the code. So _my original Colab folder has been modified_, which caused the issue.

I'll reply to this issue **_as soon as the Colab is fixed_**.
Please stay tuned and check back later.

In the meanwhile, you can run the code on your local machine. Thanks for your patience!

![image](https://user-images.githubusercontent.com/22058807/129655222-b7d4cab5-cb25-4f3d-b180-056a699390b9.png)

**Comment by thaoshibe** [comment]
We do not have plan to maintain Google Colab anymore. Sorry for the inconvenience.
