### ISSUE TITLE
About the Makeup Transfer dataset.

### ISSUE THREAD

**Issue by BIGJUN777** [VinAIResearch/CPM#11]
Thank you for releasing your nice work.

It seems the link to the [MT-Dataset](http://liusi-group.com/projects/BeautyGAN) is not available.  Could you please share your downloaded one or any accessible link?

**Comment by thaoshibe** [comment]
Hello there, thanks for your interest.
As we **do not own** the Makeup Transfer Dataset, I'm sorry to say that I can not help you.

The Makeup Transfer Dataset is published with the paper [BeautyGAN](https://dl.acm.org/doi/10.1145/3240508.3240618).
Please address the question on [BeautyGAN's repo](https://github.com/wtjiang98/BeautyGAN_pytorch/) (I saw someone has already asked about the dataset on this [issues](https://github.com/wtjiang98/BeautyGAN_pytorch/issues/12))

**Comment by BIGJUN777** [comment]
Got it. Thanks.

**Comment by thaoshibe** [comment]
I've just checked and found Makeup Transfer Dataset on my local machine.
I put it on [this Google Drive link](https://drive.google.com/file/d/1J6Q8PElIWcB-ZKd5Qmhqbu9JKbkVT_kT/view?usp=sharing). Hope this helps, but please note that **I do not guarantee this one is the official one**.

**Comment by BIGJUN777** [comment]
Cool. I appreciate your help. Thanks.
