### ISSUE TITLE
Unsatisfied results tested on customized images

### ISSUE THREAD

**Issue by BIGJUN777** [VinAIResearch/CPM#12]
Hello

I got some non-ideal results when testing the model on other images. 

1. As shown in the following image, there are some distinct boundaries on the resulting image.  Any idea on this? 

    ![image](https://user-images.githubusercontent.com/35102882/132190830-760d218b-2f4d-412a-b848-520547a1e53e.png)

   When diving into the code, I found you applied Face Detection before PRNet (See [here](https://github.com/VinAIResearch/CPM/blob/315b89dc8bef70fde99fdf4c7b3f35e9c8c2e461/utils/api.py#L67)). Because the image I input has been cropped, I commented those codes related to Face Detection in _process()_ function (See below). However, the result turned out to be worse. It seems this Face Detection is necessary. Would you provide me with more explanation on this?
    
    ![image](https://user-images.githubusercontent.com/35102882/132196776-06d146eb-b861-42a6-89ff-e078a041d3ca.png)

    ![image](https://user-images.githubusercontent.com/35102882/132198201-4f806864-24b7-432b-af15-d27e963cf26a.png)

2. When testing on my device (Tesla V100), it took several seconds to process an image, which is really time-consuming. Is this normal? If so, why will it be such time-consuming (it seems the model is not really complex)?

Looking forward to your reply. 
Thanks.

**Comment by thaoshibe** [comment]
Thanks for your interest in our work. I'm happy to help!

1. **About the boundaries**
Currently, we employed the pre-trained model of PRNet. As PRNet is not a 3D full-face model, it is expected that there will be artifacts in boundaries (Fig. 1). For better results, I suggest:
1.1. Using image blending technique
1.2. Employ other 3D full-face models. You can easily use any other 3D full-face models to replace PRNet in our framework.

![](https://raw.githubusercontent.com/YadiraF/PRNet/master/Docs/images/reconstruct.jpg)
*Fig. 1. Reconstructed face from [PRNet](https://github.com/YadiraF/PRNet)*

2. **About Face Detection**
Using face detection and cropped face ensure the quality of the PRNet (See more Issues about that [here](https://github.com/YadiraF/PRNet/issues?q=is%3Aissue+landmark)). So yes, you can comment out those codes, but it will affect the performance of the 3D face model, subsequently cause unpleasant results (as you experienced).

3. **Testing on speed**
I tested on a single RTX 1080Ti, running time ~ 1-2 seconds per image. The slowest part of the code is the 3D parts [L34-36](https://github.com/VinAIResearch/CPM/blob/315b89dc8bef70fde99fdf4c7b3f35e9c8c2e461/main.py#L34). I'd recommend you to check *whether the code is currently run on GPU or not* (As maybe tensorflow-gpu is not working).
After that, further details to speed up the 3D model parts can be found on [PRNet's repo](https://github.com/YadiraF/PRNet/issues?q=is%3Aissue+speed).

Feel free to ask if you have other questions ( ❛ᴗ❛ )

**Comment by BIGJUN777** [comment]
Thank you for your detailed as well as useful reply.

For the testing speed, as you mentioned, there is something wrong with the TensorFlow-GPU in my env. Will fix it later.
