### ISSUE TITLE
Setup throwing error

### ISSUE THREAD

**Issue by abhibhaw** [VinAIResearch/CPM#15]
Was trying to setup in on local system but conda is throwing error:

```
Solving environment: failed

ResolvePackageNotFound:
  - libstdcxx-ng=9.3.0
  - gmp=6.2.1
  - openh264=2.1.1
  - _openmp_mutex=4.5
  - jasper=1.900.1
  - readline=8.1
  - graphite2=1.3.14
  - libuuid=1.0.3
  - libxcb=1.14
  - ncurses=6.2
  - libxkbcommon=1.0.3
  - libedit=3.1.20210216
  - ld_impl_linux-64=2.33.1
  - libnghttp2=1.43.0
  - nspr=4.30
  - lame=3.100
  - cupti=10.1.168
  - nss=3.63
  - libev=4.33
  - libgcc-ng=9.3.0
  - gnutls=3.6.13
  - dbus=1.13.18
  - nettle=3.6
  - libgfortran-ng=7.3.0
  ```

Also what should be the ideal architecture to deploy this model over cloud?

**Comment by thaoshibe** [comment]
Hello there, thanks for your interest in our work.
I'd suggest that just simply install [core requirements as listed here](https://github.com/VinAIResearch/CPM#requirements).
Or, install each specific package as described in [requirements.txt](https://github.com/VinAIResearch/CPM/blob/main/requirements.txt).

Hope it helps! Feel free to ask if you have any other questions! (.❛ ᴗ ❛.)

**Comment by thaoshibe** [comment]
And this answer can be helpful as well [about machine](https://github.com/VinAIResearch/CPM/issues/9#issuecomment-879569345).

**Comment by abhibhaw** [comment]
Thanks @thaoshibe

> And this answer can be helpful as well [about machine](https://github.com/VinAIResearch/CPM/issues/9#issuecomment-879569345).
