### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint: ./PRNet/net-data/256_256_resfcn256_weight

### ISSUE THREAD

**Issue by JoJoliking** [VinAIResearch/CPM#18]
Dear Author：
I follow your running steps, but it raises an erros "ValueError: The passed save_path is not a valid checkpoint: ./PRNet/net-data/256_256_resfcn256_weight" 

color.pth, pattern.pth and 256_256_resfcn256_weight.data-00000-of-00001 are in the correct files.
Can you give me some advice?
Thank you!

**Comment by thaoshibe** [comment]
Hi there,

Please make sure that:
- `color.pth` and `pattern.pth` are in `./CPM/checkpoints`
- `256_256_resfcn256_weight.data-00000-of-00001`, `mmod_human_face_detector.dat`, and `256_256_resfcn256_weight.index` are in `./CPM/PRNet/net-data`

Or you can try to debug from here [api.py - L31](https://github.com/VinAIResearch/CPM/blob/3c43ae7c98ea6384d988aecf74ea50fed5004556/utils/api.py#L31).

**Comment by JoJoliking** [comment]
Thank a lot. I have solve this problem by downlaoding the 256_256_resfcn256_weight.index in your clolab!
