### ISSUE TITLE
MT dataset

### ISSUE THREAD

**Issue by statrav** [VinAIResearch/CPM#27]
First of all, thanks for your good work.

I think all of links of MT(makeup transfer) dataset in webs are broken(http://liusi-group.com/projects/BeautyGAN).
If you have no issues for that, can you share a MT Dataset?

Thank you.

**Comment by thaoshibe** [comment]
Hi, I do not store MT dataset in my local machine anymore.
As I'm not author of MT dataset, please refer to their repo: https://github.com/wtjiang98/BeautyGAN_pytorch/issues/12.

Thank you :D
