### ISSUE TITLE
image-invariant region mask

### ISSUE THREAD

**Issue by uestcMeng** [VinAIResearch/CPM#28]
Thank you to share your work! 
In Sec.3.2 of your paper, I find following description:
"This region mask is image-invariant and equals to a universal mask"
Does it mean all image share the same region mask? if so, can you share the region mask? I try to reproduce makeup transfer, can you show how to ues region mask to realize it? Thanks a lot.

**Comment by thaoshibe** [comment]
Yes, you're correct.
"Universal mask" is this one: https://github.com/VinAIResearch/CPM/blob/main/PRNet/uv-data/uv_face.png.
