### ISSUE TITLE
The corresponding package cannot be installed in colab and locally, because of the mac device?

### ISSUE THREAD

**Issue by QingsiLiu** [VinAIResearch/CPM#31]
Hello! The environment is inter mac，tenserflow-gpu 1.14.0 looks like it doesn't work

![image](https://github.com/VinAIResearch/CPM/assets/44899875/64064bf6-03e6-4e7b-9fcc-48338d16ddbb)

**Comment by thaoshibe** [comment]
Hello, sorry for the inconvenience you're facing.
It seems like torch==1.6.0 is out-dated.

Could you install environment with conda instead?
