### ISSUE TITLE
The performance of the code can not match the picture in README

### ISSUE THREAD

**Issue by tsuJohc** [VinAIResearch/CPM#33]
Hi, Thanks for sharing the excellent work! 

However, after successfully running the code, the results are visually worse than the demo picture in README. Are the bad results related to the code environment? Or the results are expected?

Demo picture in README:

![result](https://github.com/VinAIResearch/CPM/assets/129818160/3457cef5-db29-4094-b131-6642b9e4608e)

Results(color+pattern) after I running:

![c+p3](https://github.com/VinAIResearch/CPM/assets/129818160/7d80e2bf-c8df-40ce-a59d-fcbc276226b5)

Results(color) after I running:
![ColorOnly](https://github.com/VinAIResearch/CPM/assets/129818160/357bdcfa-4f09-443d-af63-7a5290ec8d1a)

Results(pattern) after I running:
![patternonly](https://github.com/VinAIResearch/CPM/assets/129818160/ec07de80-226e-41d1-a62f-e21c827f5bb3)

**Comment by thaoshibe** [comment]
Hello, I think for Color-Only and Pattern-Only results seems OK. (Color-Only= Only transfer the color-makeup (e.g., lipstick); Pattern-Only= Only transfer the pattern (e.g., Moon-shape on forehead)).

For the randomness, I think you might try to vary the alpha of blending function [here](https://github.com/VinAIResearch/CPM/blob/b12e83f195f6c3d378b93bb62da2fcdeb52f1312/main.py#L48).
Also, I'd suggest to check segmentation-mask results [https://github.com/VinAIResearch/CPM/blob/b12e83f195f6c3d378b93bb62da2fcdeb52f1312/main.py#L45] to see if it's consistent each time.
Personally, I never run into cases where the results are not consistent (like you're facing). Maybe change the alpha in blending function should help!

**Comment by thaoshibe** [comment]
You can vary it from 0 to 1.
