### ISSUE TITLE
The sticker order in the Stickers dataset is incorrect

### ISSUE THREAD

**Issue by yltqy** [VinAIResearch/CPM#35]
I want to stick stickers on my own dataset, but the mask name in CPM-Synt-1 does not correspond.
![b3130d5de204ae2aa7d5f30a6f9e0e9](https://github.com/VinAIResearch/CPM/assets/115929004/f090a09c-8e9c-4160-bf6c-ad843cd4a52d)
![0845078d848b34009630bf8cd536063](https://github.com/VinAIResearch/CPM/assets/115929004/04975582-646c-44d4-8e6a-160d2aa15d9e)

**Comment by yltqy** [comment]
May I ask if the code for pasting stickers can be published?

**Comment by thaoshibe** [comment]
Hello, sorry for the very late response (I'm not longer working for VinAI Research (and this repo is not actively maintained now...
So the best way to reach me is email.

Anyway, for your question -- The the segmentation mask you are seeing is **the segmentation mask of the sticker that pasted on the face**, not the segmentation mask of the sticker itself.

For example, `makeup_23_patt143.png` is the segmentation mask of pasting the sticker 143 (sticker filename 143.png) on the makeup image 23 (makeup file name 23.png).

Hope that explains your issue ^^

**Comment by thaoshibe** [comment]
Unfortunately, I do not have the sticker-rendering code in hand.
However, I directly get that code from https://github.com/yfeng95/PRNet?tab=readme-ov-file#texture-editing -- In which, in our case, you need to prepare the new texture with the sicker.

Thank you!
