### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by Yueming6568** [VinAIResearch/CPM#4]
Thanks for your great work!
Will you release the training code ??

**Comment by thaoshibe** [comment]
Thank you!

You can find training code here: https://github.com/VinAIResearch/CPM#training-and-evaluation

**Comment by thaoshibe** [comment]
Have you got the answer?
- Training code for **Color Branch**: [here](https://github.com/VinAIResearch/CPM/tree/main/Color)
- Training code for **Pattern Branch**: [here](https://github.com/VinAIResearch/CPM/tree/main/Pattern)

Please close this issue if there's no other question. Thank you!

**Comment by Yueming6568** [comment]
Thank you for your answer ! I will try it ~
