### ISSUE TITLE
Can you publish data preprocessing code?

### ISSUE THREAD

**Issue by bladenow** [VinAIResearch/CPM#7]
Thank you very much for your great work!
Can you publish data preprocessing code?
Is there no code to extract the mask or I missed it

I want to experiment with dark environments and complex lighting,
 I need to build my own data set
So I need the code to extract the masks

**Comment by thaoshibe** [comment]
Thanks for your interest! (🖒^^)🖒
To be clear, could you provide more details about the "mask"? (Eg: facial segmentation, UV-map-segmentation, etc.).
Without further information, I'm not sure I can address your question properly.

-----

But in general, I hope you're looking for "one of these masks": facial segmentation or UV-segmentation

##### Facial Segmentation

To get facial segmentation, I used [[face-parsing.Pytorch](https://github.com/zllrunning/face-parsing.PyTorch)]

<img src="https://user-images.githubusercontent.com/22058807/119296332-f2310000-bc82-11eb-8b16-fd22c8cc8912.png" alt="facial-segmentation" width="100"/>

_(Face-parsing will give you facial attributes such as upper lip, lower lip, left eye, right eye, hair, etc. Check [here ](https://github.com/zllrunning/face-parsing.PyTorch/blob/d2e684cf1588b46145635e8fe7bcc29544e5537e/prepropess_data.py#L17)for details)_

P.s: Existing makeup datasets ([LADN](https://georgegu1997.github.io/LADN-project-page/), [BeautyGAN](http://www.colalab.org/projects/BeautyGAN)) already have facial segmentation within them.

##### UV-map-segmentation

Check how to get ["respective UV-map texture of each image and its segmentation mask"](https://github.com/VinAIResearch/CPM/tree/main/Color#color-makeup---training-guideline), section 2 - Get UV texture
(To be specific, uv_seg is what's you need)
https://github.com/VinAIResearch/CPM/blob/315b89dc8bef70fde99fdf4c7b3f35e9c8c2e461/Color/create_beautygan_uv.py#L51

---

Glad to help! ᕦ( ͡° ͜ʖ ͡°)ᕤ

**Comment by bladenow** [comment]
all
|__ images
	|__ makeup
	|__ non-makeup
|__ segs
	|__ makeup
	|__ non-makeup

**Comment by bladenow** [comment]
Thank you very much for your reply so soon.
SEGS directory, with what code?
----------------
|__ images
	|__ makeup
	|__ non-makeup
|__ segs
	|__ makeup
	|__ non-makeup

**Comment by thaoshibe** [comment]
Hello, which dataset you're talking about?
CPM-Synt-1, CPM-Synt-2, or Makeup Transfer Dataset? Pls check [here ](https://github.com/VinAIResearch/CPM/blob/main/about-data.md)

**Comment by bladenow** [comment]
I want to train with my own data set
Because the pre training model, some dark and complex light samples, the effect is not very good.
Is SEG processed with this file（create_beautygan_uv.py）
or
the [prepropess_data.py](https://github.com/zllrunning/face-parsing.PyTorch/blob/d2e684cf1588b46145635e8fe7bcc29544e5537e/prepropess_data.py#L17)

**Comment by thaoshibe** [comment]
Oh I think you're talking about [Makeup Transfer Dataset](http://liusi-group.com/projects/BeautyGAN) (published with BeautyGAN paper).
In their paper, they said that they used PSPNet. Please check in their paper.

For me, I recommend using [face-parsing.Pytorch](https://github.com/zllrunning/face-parsing.PyTorch). Please check!

**Comment by bladenow** [comment]
> 哦，我认为您是在谈论“[化妆转移数据集”](http://liusi-group.com/projects/BeautyGAN)（与BeautyGAN论文一起发布）。他们已经提供了面部分割面膜！
> 
> 他们在论文中说，他们使用了PSPNet。请检查他们的论文。
> 
> 对我来说，我建议使用[face-parsing.Pytorch](https://github.com/zllrunning/face-parsing.PyTorch)。请检查！

Thank you very much！！！
