### ISSUE TITLE
There are no  uv-map texture results after i runned this code.

### ISSUE THREAD

**Issue by pirate-zhang** [VinAIResearch/CPM#8]
Hi,there are no  uv-map texture results after i runned this code.It only produces an empty folder named save_folder.
What's the matter, please?

**Comment by thaoshibe** [comment]
Hi there,
Please make sure that `--path` [(line 14)](https://github.com/VinAIResearch/CPM/blob/315b89dc8bef70fde99fdf4c7b3f35e9c8c2e461/Color/create_beautygan_uv.py#L14) is pointing to `your image folder`.

For example, if your image folder is `/home/image/folder`, then: `python create_beautygan_uv.py --path /home/image/folder --savedir /path/to/save_folder` should work.

**Comment by pirate-zhang** [comment]
Hi,Thank you for your reply！


It has shown that the new picture is saved in the folder, but I didn't see the picture after opening the folder. I changed the 1 code to this one, but it still can't work.


python create_beautygan_uv.py --path /home/zhangwei/CPM-main/Color/data --savedir /home/zhangwei/CPM-main/Color//save_folder












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VinAIResearch/CPM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VinAIResearch/CPM] There are no  uv-map texture results after i runned this code. (#8)





 
Hi there,
 Please make sure that --path (line 14) is pointing to your image folder.
 
For example, if your image folder is /home/image/folder, then: python create_beautygan_uv.py --path /home/image/folder --savedir /path/to/save_folder should work.

**Comment by thaoshibe** [comment]
Hi there, please change [(line 30)](https://github.com/VinAIResearch/CPM/blob/315b89dc8bef70fde99fdf4c7b3f35e9c8c2e461/Color/create_beautygan_uv.py#L30):

`list_imgs = glob.glob(os.path.join(args.path, "images", "*", "*.png"))`

to:

`list_imgs = glob.glob(os.path.join(args.path, "*.png"))` 

and see if it works.

**Comment by thaoshibe** [comment]
And as read in [README.md](https://github.com/VinAIResearch/CPM/tree/main/Color#color-makeup---training-guideline), to run the code successfully, please make sure **the dataset folder follows THIS STRUCTURE:**
```
all
|__ images
	|__ makeup
	|__ non-makeup
|__ segs
	|__ makeup
	|__ non-makeup
```

Else, I'm sorry to say that I can not help you. Hope this helps! ( ´ ▽ ` )b

**Comment by pirate-zhang** [comment]
Thank you very much for your reply. I'll try to debug the code here





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VinAIResearch/CPM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 上午10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VinAIResearch/CPM] There are no  uv-map texture results after i runned this code. (#8)





 
And as read in README.md, to run the code successfully, please make sure the dataset folder follows THIS STRUCTURE:
 all |__ images 	|__ makeup 	|__ non-makeup |__ segs 	|__ makeup 	|__ non-makeup  
Else, I'm sorry to say that I can not help you. Hope this helps! ( ´ ▽ ` )b

**Comment by thaoshibe** [comment]
You're more than welcome ( ´ ▽ ` )b
Feel free to ask if you have any other questions.

**Comment by pirate-zhang** [comment]
Hi, I'm sorry to disturb you again.Firstly, I want to tell you that I got the Segmentation Mask&nbsp; of the images like this.

But when i change&nbsp; uv_texture, uv_seg = generator.get_texture(image, seg)
to try: uv_texture, uv_seg = generator.get_texture(image, seg) except: print('Something wrong with: ', list_imgs[i])
it will report an error like this:
Traceback (most recent call last):
&nbsp; File "create_beautygan_uv.py", line 55, in <module&gt;
&nbsp; &nbsp; cv2.imwrite(os.path.join(args.savedir, "images", filenames[i]), uv_texture)
NameError: name 'uv_texture' is not defined
So it's not generated UV-texture.The folder of segs have no change like this.



In view of this situation, how should I deal with it? Please give me some advice! Thanks a lot~





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VinAIResearch/CPM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 上午10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VinAIResearch/CPM] There are no  uv-map texture results after i runned this code. (#8)





 
You're more than welcome ( ´ ▽ ` )b
 Feel free to ask if you have any other questions.
